# استخدام Node 20 أثناء البناء والتشغيل
[build.environment]
  NODE_VERSION = "20"

# إعدادات وظائف Netlify
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@google/generative-ai"]

# مهلة وظيفة generateHeadlines
[functions."generateHeadlines"]
  timeout = 26
