# يحدد إصدار Node.js لضمان التوافق أثناء بناء الموقع
[build.environment]
  NODE_VERSION = "20"

# يحدد جدول التشغيل لدالة توليد المقالات
[functions."article-generator"]
  # هذا التعبير يعني "نفذ هذه الدالة في الدقيقة صفر من كل ساعة"
  schedule = "0 * * * *"
