import type { Article } from '../types';

const today = new Date();
const yesterday = new Date();
yesterday.setDate(today.getDate() - 1);

const todayISO = today.toISOString();
const yesterdayISO = yesterday.toISOString();

export const MOCK_ARTICLES: { [key: string]: Article[] } = {
  ar: [
    {
      id: 'mock-ar-1',
      headline: 'إطلاق قمر صناعي جديد لرصد تغير المناخ بدقة غير مسبوقة',
      byline: 'وكالة الفضاء الدولية',
      date: todayISO,
      body: 'أعلنت وكالة الفضاء الدولية اليوم عن إطلاق القمر الصناعي "عين الأرض ٣"، الذي يهدف إلى مراقبة التغيرات المناخية وتأثيراتها على كوكبنا.\nالجهاز الجديد مزود بأجهزة استشعار متطورة قادرة على قياس مستويات ثاني أكسيد الكربون ودرجات حرارة المحيطات بدقة لم يسبق لها مثيل، مما سيوفر للعلماء بيانات حيوية لفهم أزمة المناخ بشكل أفضل.',
      imageUrl: 'https://picsum.photos/seed/space-ar/1280/720',
      imagePrompt: 'صورة واقعية لقمر صناعي يدور حول الأرض، مع ظهور القارات بوضوح',
      category: 'Technology',
      viralityDescription: 'سريع الانتشار',
      comments: [{ author: 'نورة', text: 'خبر رائع! نأمل أن يساعد هذا في إيجاد حلول.' }],
      sources: [{ title: 'موقع وكالة الفضاء', uri: '#' }],
    },
    {
      id: 'mock-ar-2',
      headline: 'اكتشافات أثرية مذهلة تغير فهمنا للتاريخ القديم',
      byline: 'قسم الآثار الوطني',
      date: todayISO,
      body: 'كشف فريق من علماء الآثار عن مدينة قديمة كانت مدفونة تحت الرمال لآلاف السنين. تحتوي المدينة على مبانٍ سليمة وأدوات فنية متقنة، مما يشير إلى وجود حضارة متقدمة لم تكن معروفة من قبل.\nهذا الاكتشاف قد يعيد كتابة فصول كاملة من تاريخ المنطقة، ويقدم رؤى جديدة حول كيفية عيش المجتمعات القديمة وتفاعلها.',
      imageUrl: 'https://picsum.photos/seed/ruins-ar/1280/720',
      imagePrompt: 'صورة لعلماء آثار يكشفون عن جدارية قديمة في موقع حفر أثري تحت ضوء الشمس',
      category: 'World',
      viralityDescription: 'متوسط الانتشار',
      comments: [{ author: 'أحمد', text: 'مذهل! لا أستطيع الانتظار لمعرفة المزيد.' }],
      sources: [{ title: 'المجلة الأثرية', uri: '#' }],
    },
    {
      id: 'mock-ar-3',
      headline: 'فريق كرة السلة المحلي يفوز بالبطولة في اللحظات الأخيرة',
      byline: 'القسم الرياضي',
      date: yesterdayISO,
      body: 'في مباراة مثيرة حبست الأنفاس، تمكن فريق "صقور المدينة" من تحقيق فوز دراماتيكي على منافسه التقليدي بنتيجة ٩٨-٩٧. جاء الفوز بفضل رمية ثلاثية في الثانية الأخيرة من عمر المباراة، مما أدى إلى تتويج الفريق بلقب البطولة للمرة الأولى منذ عشر سنوات.',
      imageUrl: 'https://picsum.photos/seed/basketball-ar/1280/720',
      imagePrompt: 'لقطة حركة للاعب كرة سلة يسدد رمية حاسمة في اللحظات الأخيرة من المباراة',
      category: 'Sports',
      viralityDescription: 'قليل الانتشار',
      comments: [{ author: 'خالد', text: 'أفضل مباراة رأيتها في حياتي! أبطال!' }],
      sources: [],
    },
    {
      id: 'mock-ar-4',
      headline: 'البرلمان يصادق على قانون جديد لتعزيز الاستثمار',
      byline: 'المراسل السياسي',
      date: todayISO,
      body: 'صادق البرلمان بالإجماع على مشروع قانون جديد يهدف إلى تسهيل الإجراءات الإدارية وتشجيع الاستثمار المحلي والأجنبي. يتضمن القانون إعفاءات ضريبية للمشاريع الناشئة وتبسيط إجراءات الترخيص.\nوأكد رئيس البرلمان أن هذا القانون يمثل خطوة مهمة نحو تحسين مناخ الأعمال وخلق فرص عمل جديدة للشباب.',
      imageUrl: 'https://images.pexels.com/photos/8112189/pexels-photo-8112189.jpeg',
      imagePrompt: 'صورة لقاعة البرلمان أثناء جلسة تصويت مهمة',
      category: 'Politics',
      viralityDescription: 'سريع الانتشار',
      comments: [{ author: 'فاطمة', text: 'خطوة إيجابية للاقتصاد' }],
      sources: [{ title: 'البوابة الرسمية', uri: '#' }],
    },
    {
      id: 'mock-ar-5',
      headline: 'افتتاح مركز صحي جديد يخدم أكثر من 50 ألف مواطن',
      byline: 'محرر الأخبار المحلية',
      date: todayISO,
      body: 'افتتح محافظ المدينة صباح اليوم المركز الصحي الجديد في الحي الشمالي، والذي سيوفر خدمات طبية متكاملة لأكثر من 50 ألف مواطن. المركز مجهز بأحدث الأجهزة الطبية ويضم عيادات متخصصة في مختلف المجالات.\nوأشار المحافظ إلى أن هذا المشروع يأتي ضمن خطة شاملة لتطوير البنية التحتية الصحية في جميع أحياء المدينة.',
      imageUrl: 'https://images.pexels.com/photos/236380/pexels-photo-236380.jpeg',
      imagePrompt: 'صورة لمبنى مركز صحي حديث من الخارج',
      category: 'Local',
      viralityDescription: 'متوسط الانتشار',
      comments: [{ author: 'محمد', text: 'أخيراً! كنا بحاجة ماسة لهذا المركز' }],
      sources: [{ title: 'بلدية المدينة', uri: '#' }],
    },
    {
      id: 'mock-ar-6',
      headline: 'شركة تقنية محلية تحصل على تمويل بقيمة 10 ملايين دولار',
      byline: 'قسم الأعمال',
      date: yesterdayISO,
      body: 'أعلنت شركة "تك فيوتشر" الناشئة المتخصصة في تطوير حلول الذكاء الاصطناعي عن حصولها على تمويل بقيمة 10 ملايين دولار من مجموعة مستثمرين محليين ودوليين. ستستخدم الشركة التمويل لتوسيع فريقها وتطوير منتجات جديدة.\nهذا التمويل يؤكد على نمو قطاع التقنية المحلي وقدرته على المنافسة عالمياً.',
      imageUrl: 'https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg',
      imagePrompt: 'صورة لفريق شركة ناشئة في مكتب عصري',
      category: 'Business',
      viralityDescription: 'سريع الانتشار',
      comments: [{ author: 'سارة', text: 'فخورة بالشركات المحلية!' }],
      sources: [{ title: 'مجلة الأعمال', uri: '#' }],
    }
  ],
  en: [
    {
      id: 'mock-en-1',
      headline: 'New Satellite Launched to Monitor Climate Change with Unprecedented Accuracy',
      byline: 'International Space Agency',
      date: todayISO,
      body: 'The International Space Agency announced today the launch of the "Earth Eye 3" satellite, aimed at monitoring climate change and its effects on our planet.\nThe new device is equipped with advanced sensors capable of measuring carbon dioxide levels and ocean temperatures with unparalleled precision, which will provide scientists with vital data to better understand the climate crisis.',
      imageUrl: 'https://picsum.photos/seed/space-en/1280/720',
      imagePrompt: 'A realistic photo of a satellite orbiting Earth, with the continents clearly visible',
      category: 'Technology',
      viralityDescription: 'Fast Spreading',
      comments: [{ author: 'John', text: 'Great news! Hope this helps find solutions.' }],
      sources: [{ title: 'Space Agency Website', uri: '#' }],
    },
    {
      id: 'mock-en-2',
      headline: 'Stunning Archaeological Find Changes Understanding of Ancient History',
      byline: 'National Antiquities Dept.',
      date: todayISO,
      body: 'A team of archaeologists has uncovered an ancient city that was buried under sand for thousands of years. The city contains intact buildings and elaborate artifacts, suggesting an advanced civilization previously unknown.\nThis discovery could rewrite entire chapters of the region\'s history, offering new insights into how ancient societies lived and interacted.',
      imageUrl: 'https://picsum.photos/seed/ruins-en/1280/720',
      imagePrompt: 'A photo of archaeologists uncovering an ancient mural at a dig site in the sunlight',
      category: 'World',
      viralityDescription: 'Medium Spreading',
      comments: [{ author: 'Sarah', text: 'Amazing! Can\'t wait to learn more.' }],
      sources: [{ title: 'Journal of Archaeology', uri: '#' }],
    },
    {
      id: 'mock-en-3',
      headline: 'Local Basketball Team Wins Championship with Last-Second Shot',
      byline: 'Sports Desk',
      date: yesterdayISO,
      body: 'In a thrilling game that went down to the wire, the "City Falcons" secured a dramatic 98-97 victory over their rivals. The win came from a three-point shot in the final second of the game, crowning the team as champions for the first time in a decade.',
      imageUrl: 'https://picsum.photos/seed/basketball-en/1280/720',
      imagePrompt: 'An action shot of a basketball player making a game-winning shot at the buzzer',
      category: 'Sports',
      viralityDescription: 'Low Spreading',
      comments: [{ author: 'Mike', text: 'Best game I\'ve ever seen! Champions!' }],
      sources: [],
    },
    {
      id: 'mock-en-4',
      headline: 'Parliament Approves New Law to Boost Investment',
      byline: 'Political Correspondent',
      date: todayISO,
      body: 'Parliament unanimously approved a new law aimed at simplifying administrative procedures and encouraging domestic and foreign investment. The law includes tax exemptions for startups and streamlined licensing procedures.\nThe Speaker of Parliament emphasized that this legislation represents an important step toward improving the business climate and creating new job opportunities for youth.',
      imageUrl: 'https://images.pexels.com/photos/8112189/pexels-photo-8112189.jpeg',
      imagePrompt: 'Photo of parliament chamber during an important voting session',
      category: 'Politics',
      viralityDescription: 'Fast Spreading',
      comments: [{ author: 'Emma', text: 'Positive step for the economy' }],
      sources: [{ title: 'Official Portal', uri: '#' }],
    },
    {
      id: 'mock-en-5',
      headline: 'New Health Center Opens to Serve Over 50,000 Citizens',
      byline: 'Local News Editor',
      date: todayISO,
      body: 'The city mayor opened the new health center in the northern district this morning, which will provide comprehensive medical services to more than 50,000 citizens. The center is equipped with the latest medical devices and includes specialized clinics in various fields.\nThe mayor noted that this project is part of a comprehensive plan to develop health infrastructure across all city neighborhoods.',
      imageUrl: 'https://images.pexels.com/photos/236380/pexels-photo-236380.jpeg',
      imagePrompt: 'Photo of a modern health center building exterior',
      category: 'Local',
      viralityDescription: 'Medium Spreading',
      comments: [{ author: 'David', text: 'Finally! We desperately needed this center' }],
      sources: [{ title: 'City Municipality', uri: '#' }],
    },
    {
      id: 'mock-en-6',
      headline: 'Local Tech Company Secures $10 Million Funding',
      byline: 'Business Desk',
      date: yesterdayISO,
      body: 'TechFuture, a startup specializing in AI solutions development, announced securing $10 million in funding from a group of local and international investors. The company will use the funding to expand its team and develop new products.\nThis funding confirms the growth of the local tech sector and its ability to compete globally.',
      imageUrl: 'https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg',
      imagePrompt: 'Photo of a startup team in a modern office',
      category: 'Business',
      viralityDescription: 'Fast Spreading',
      comments: [{ author: 'Lisa', text: 'Proud of local companies!' }],
      sources: [{ title: 'Business Magazine', uri: '#' }],
    }
  ],
};