// This file was generated by a tool to ensure accuracy.
// Do not edit manually.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      friendships: {
        Row: {
          created_at: string
          friend_id: string
          id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          friend_id: string
          id?: string
          user_id: string
        }
        Update: {
          created_at?: string
          friend_id?: string
          id?: string
          user_id?: string
        }
      }
      messages: {
        Row: {
          article_id: string | null
          content: string
          created_at: string
          id: string
          is_read: boolean
          receiver_id: string
          sender_id: string
        }
        Insert: {
          article_id?: string | null
          content: string
          created_at?: string
          id?: string
          is_read?: boolean
          receiver_id: string
          sender_id: string
        }
        Update: {
          article_id?: string | null
          content?: string
          created_at?: string
          id?: string
          is_read?: boolean
          receiver_id?: string
          sender_id?: string
        }
      }
      news_articles: {
        Row: {
          author: string
          category: string
          content: string
          created_at: string
          description: string
          id: string
          image_url: string
          language: string
          published_at: string
          source_name: string
          source_url: string
          title: string
          virality_description: string | null
        }
        Insert: {
          author: string
          category: string
          content: string
          created_at?: string
          description: string
          id?: string
          image_url: string
          language: string
          published_at: string
          source_name: string
          source_url: string
          title: string
          virality_description?: string | null
        }
        Update: {
          author?: string
          category?: string
          content?: string
          created_at?: string
          description?: string
          id?: string
          image_url?: string
          language?: string
          published_at?: string
          source_name?: string
          source_url?: string
          title?: string
          virality_description?: string | null
        }
      }
      profiles: {
        Row: {
          display_name: string
          id: string
          updated_at: string | null
          username: string
        }
        Insert: {
          display_name: string
          id: string
          updated_at?: string | null
          username: string
        }
        Update: {
          display_name?: string
          id?: string
          updated_at?: string | null
          username?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
