import type { Category } from './types';

export const APP_VERSION = '1.5.0'; // Version identifier

export const CATEGORIES: Category[] = ['World', 'Technology', 'Sports', 'Business', 'Local'];

export const MOOD_FILTERS = {
  en: [
    { key: 'all', label: 'All News' },
    { key: 'breaking', label: 'Breaking News' },
    { key: 'deep_dive', label: 'Deep Dives' },
    { key: 'uplifting', label: 'Uplifting Stories' },
    { key: 'future_tech', label: 'Future Tech' },
  ],
  ar: [
    { key: 'all', label: 'كل الأخبار' },
    { key: 'breaking', label: 'أخبار عاجلة' },
    { key: 'deep_dive', label: 'تحليلات عميقة' },
    { key: 'uplifting', label: 'قصص ملهمة' },
    { key: 'future_tech', label: 'تكنولوجيا المستقبل' },
  ]
}

export const UI_TEXT = {
  en: {
    title: 'suhf',
    subtitle: 'Freshly AI-Generated News from Around the World',
    language_toggle: 'العربية',
    generating_title: 'Generating Today\'s Edition...',
    generating_subtitle: 'Our AI journalists are hard at work. Please wait a moment.',
    error_title: 'Failed to Generate Articles',
    error_cache_title: 'Application Out of Date',
    error_cache_body: 'Your browser is running an old version of the app from its cache. Please perform a hard refresh (Ctrl+Shift+R or Cmd+Shift+R) to load the latest version.',
    config_error_title: "Configuration Error",
    config_error_gemini: "The backend is not configured with a Gemini API key. For local development, create a `.env` file and add `API_KEY=\"YOUR_KEY\"`. For deployment, ensure the `API_KEY` environment variable is set in your platform's settings.",
    config_error_firebase: "Firebase is not configured. Please open the `config.js` file, fill in your Firebase project details, save, and then **re-deploy** the site for login/comments to work.",
    error_subtitle: 'There was an issue connecting to our news desk. Please try again later.',
    error_gemini_invalid_key: "The provided API key is not valid. Please check for typos or get a new key.",
    error_gemini_quota: "You have exceeded your free quota or billing limit. Please check your billing status on Google Cloud to increase your quota, or try again later.",
    error_gemini_json: "The AI returned an unexpected response. Please try refreshing.",
    manage_billing_link: "Manage Billing on Google Cloud",
    read_more: 'Read More',
    by: 'By',
    search_placeholder: 'Search articles...',
    refresh_tooltip: 'Get latest edition',
    account_tooltip: 'My Account',
    share_article: 'Share this article:',
    copy_link_success: 'Link copied!',
    virality_tooltip: 'Virality: How widely this story is spreading based on real-world data.',
    login: 'Login',
    logout: 'Logout',
    comments_title: 'Reader Comments',
    add_comment_placeholder: 'Add your comment...',
    post_comment: 'Post Comment',
    login_to_comment: 'Please log in to post a comment.',
    share_suhuf: 'Share with suhf Friends',
    share_whatsapp: 'Share on WhatsApp',
    share_telegram: 'Share on Telegram',
    fast_spreading: 'Fast Spreading',
    medium_spreading: 'Medium Spreading',
    low_spreading: 'Low Spreading',
    unknown: 'Virality Unknown',
    sources: 'Sources',
    mood_filter_prompt: 'What are you interested in today?',
    loading_older_articles: 'Loading older articles...',
    new_edition_available: 'New edition available!',
    click_to_refresh: 'Click to refresh',
    login_failed_title: 'Login Failed',
    login_failed_body: 'Could not sign you in. Please ensure pop-ups are not blocked by your browser and try again. There might be a configuration issue with the site\'s authentication provider.',
    ok_button: 'OK',
  },
  ar: {
    title: 'صحف',
    subtitle: 'أخبار عاجلة تم إنشاؤها بواسطة الذكاء الاصطناعي',
    language_toggle: 'English',
    generating_title: 'جاري إعداد نسخة اليوم...',
    generating_subtitle: 'صحفيونا الآليون يعملون بجد. الرجاء الانتظار لحظة.',
    error_title: 'فشل في توليد المقالات',
    error_cache_title: 'التطبيق غير محدّث',
    error_cache_body: 'يستخدم متصفحك نسخة قديمة من التطبيق من الذاكرة المؤقتة. الرجاء القيام بإعادة تحميل كاملة للصفحة (Ctrl+Shift+R أو Cmd+Shift+R) لتحميل أحدث إصدار.',
    config_error_title: "خطأ في الإعدادات",
    config_error_gemini: "الواجهة الخلفية غير مهيأة بمفتاح Gemini API. للتطوير المحلي، أنشئ ملف `.env` وأضف `API_KEY=\"YOUR_KEY\"`. للنشر، تأكد من تعيين متغير البيئة `API_KEY` في إعدادات منصة النشر.",
    config_error_firebase: "Firebase غير مهيأ. الرجاء فتح ملف `config.js`، وتعبئة بيانات مشروع Firebase، ثم الحفظ، ثم **إعادة نشر** الموقع لتعمل ميزات تسجيل الدخول والتعليقات.",
    error_subtitle: 'حدثت مشكلة في الاتصال بمكتب الأخبار. يرجى المحاولة مرة أخرى في وقت لاحق.',
    error_gemini_invalid_key: "مفتاح API المُقدَّم غير صالح. يرجى التحقق من الأخطاء الإملائية أو الحصول على مفتاح جديد.",
    error_gemini_quota: "لقد تجاوزت حصتك المجانية أو حد الفوترة. يرجى التحقق من حالة الفوترة في Google Cloud لزيادة الحصة، أو المحاولة مرة أخرى لاحقًا.",
    error_gemini_json: "أعاد الذكاء الاصطناعي استجابة غير متوقعة. يرجى محاولة التحديث.",
    manage_billing_link: "إدارة الفوترة على Google Cloud",
    read_more: 'اقرأ المزيد',
    by: 'بقلم',
    search_placeholder: 'ابحث في المقالات...',
    refresh_tooltip: 'احصل على الإصدار الأخير',
    account_tooltip: 'حسابي',
    share_article: 'شارك هذا المقال:',
    copy_link_success: 'تم نسخ الرابط!',
    virality_tooltip: 'مؤشر الانتشار: مدى انتشار هذه القصة بناءً على بيانات حقيقية.',
    login: 'تسجيل الدخول',
    logout: 'تسجيل الخروج',
    comments_title: 'تعليقات القراء',
    add_comment_placeholder: 'أضف تعليقك...',
    post_comment: 'نشر التعليق',
    login_to_comment: 'الرجاء تسجيل الدخول لنشر تعليق.',
    share_suhuf: 'شارك مع أصدقاء صحف',
    share_whatsapp: 'شارك عبر واتساب',
    share_telegram: 'شارك عبر تيليجرام',
    fast_spreading: 'سريع الانتشار',
    medium_spreading: 'متوسط الانتشار',
    low_spreading: 'قليل الانتشار',
    unknown: 'انتشار غير معروف',
    sources: 'المصادر',
    mood_filter_prompt: 'ما الذي يثير اهتمامك اليوم؟',
    loading_older_articles: 'جاري تحميل المقالات الأقدم...',
    new_edition_available: 'إصدار جديد متوفر!',
    click_to_refresh: 'اضغط للتحديث',
    login_failed_title: 'فشل تسجيل الدخول',
    login_failed_body: 'تعذر تسجيل دخولك. يرجى التأكد من عدم حظر النوافذ المنبثقة بواسطة متصفحك والمحاولة مرة أخرى. قد تكون هناك مشكلة في إعدادات المصادقة للموقع.',
    ok_button: 'حسناً',
  }
};

export const DYNAMIC_UI_TEXT = {
  en: {
    fetching_headlines: (date: string) => `Fetching headlines for ${date}`,
    contacting_news_desk: 'Contacting the news desk...',
    writing_articles: (day: string) => `Writing articles for ${day}`,
    crafting_stories: 'Our AI is crafting the stories...',
    developing_photos: (day: string) => `Developing photos for ${day}`,
    bringing_stories_to_life: 'Bringing the stories to life...',
    finding_mood_stories: (mood: string) => `Finding "${mood}" stories...`,
    curating_feed: 'Our AI is curating your feed.',
  },
  ar: {
    fetching_headlines: (date: string) => `جاري جلب العناوين الرئيسية ليوم ${date}`,
    contacting_news_desk: 'جاري الاتصال بمكتب الأخبار...',
    writing_articles: (day: string) => `جاري كتابة مقالات لـ ${day}`,
    crafting_stories: 'يعمل الذكاء الاصطناعي على صياغة القصص...',
    developing_photos: (day: string) => `جاري تحميض الصور لـ ${day}`,
    bringing_stories_to_life: 'إضفاء الحيوية على القصص...',
    finding_mood_stories: (mood: string) => `جاري البحث عن قصص "${mood}"...`,
    curating_feed: 'يعمل الذكاء الاصطناعي على تنظيم خلاصتك.',
  }
};

export const CATEGORY_MAP = {
  en: {
    World: 'World News',
    Technology: 'Technology',
    Sports: 'Sports',
    Business: 'Business',
    Local: 'Local News',
  },
  ar: {
    World: 'أخبار العالم',
    Technology: 'تكنولوجيا',
    Sports: 'رياضة',
    Business: 'أعمال',
    Local: 'أخبار محلية',
  }
}